#!/usr/bin/env bash

#:: Adeptio dev team
#:: Copyright // 2019-01-05
#:: Version: v2.0.0.0

set -e
Intall_log='/tmp/adeptiocore_install.log'

# Check if bitcoin repo exists for Xenial //
file="/etc/apt/sources.list.d/bitcoin-ubuntu-bitcoin-xenial.list"
if [ -e "$file" ]; then
    echo "" &> /dev/null
else
sudo add-apt-repository ppa:bitcoin/bitcoin -y &>> $Intall_log
sudo apt update -y &>> $Intall_log
fi

# Check if bitcoin repo exists for Bionic //
file="/etc/apt/sources.list.d/bitcoin-ubuntu-bitcoin-bionic.list"
if [ -e "$file" ]; then
    echo "" &> /dev/null
else
sudo add-apt-repository ppa:bitcoin/bitcoin -y &>> $Intall_log
sudo apt update -y &>> $Intall_log
fi

# Check if we have adeptiocore.service?
file="/etc/systemd/system/adeptiocore.service"
if [ -e "$file" ]; then 
    sudo systemctl stop adeptiocore
else
    echo "" &> /dev/null
fi
