#!/usr/bin/env bash

#:: Adeptio dev team
#:: Copyright // 2019-01-08
#:: Version: v2.0.0.0

set -e

# Check if adeptiocore.service exist?
file="/etc/systemd/system/adeptiocore.service"
if [ -e "$file" ]; then
    sudo systemctl stop adeptiocore.service
    rm /etc/systemd/system/adeptiocore.service
    sudo systemctl daemon-reload
else
    echo "" &> /dev/null
fi

# Remove binary's
rm -fr /usr/bin/adeptiod
rm -fr /usr/bin/adeptio-cli

# Remove status checker
sudo rm -fr /usr/bin/adeptiocore-*
