#!/usr/bin/env bash

#:: Adeptio dev team
#:: Copyright // 2019-01-08
#:: Version: v2.0.0.0

set -e
Intall_log='/var/log/syslog'

echo 'Installing adeptiocore...'

# Check if we have adeptiocore.service?
file="/etc/systemd/system/adeptiocore.service"

if [ -e "$file" ]; then
    echo "" &> /dev/null
else
cat << EOF > /etc/systemd/system/adeptiocore.service
[Unit]
Description=Adeptio Core Wallet daemon & service
After=network.target
[Service]
User=$(echo $USER)
Type=forking
ExecStart=/usr/bin/adeptiod -daemon -pid=$(echo $HOME)/.adeptio/adeptiod.pid --datadir=$(echo $HOME)/.adeptio/
PIDFile=$(echo $HOME)/.adeptio/adeptiod.pid
ExecStop=/usr/bin/adeptio-cli stop
Restart=always
RestartSec=3600
TimeoutStopSec=60s
TimeoutStartSec=10s
StartLimitInterval=120s
StartLimitBurst=5
[Install]
WantedBy=default.target
EOF
fi

sudo systemctl enable adeptiocore

# Change perm:
sudo chmod 664 /etc/systemd/system/adeptiocore.service

# Check if adeptio.conf is empty?
file2="~/.adeptio/adeptio.conf"
if [ -e "$file2" ]; then
    echo "" &> /dev/null
else
echo 'Configuring adeptiocore for the first time...'
mkdir -p ~/.adeptio/
touch ~/.adeptio/adeptio.conf
cat << EOF > ~/.adeptio/adeptio.conf
rpcuser=adeptiocoreuser
rpcpassword=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 32 ; echo '')
rpcallow=127.0.0.1
server=1
listen=1
daemon=1
staking=1
enablezeromint=0
EOF
fi

echo 'AdeptioCore successfully installed...'
