#!/usr/bin/env bash

#:: Adeptio dev team
#:: Copyright // 2019-03-26
#:: Version: v1.2

set -e
Intall_log='/var/log/syslog'

echo 'Installing storade-server...'

test -e /etc/systemd/system/storADEserver.service || echo 'Downloading latest storADE code from Github...'
test -e /etc/systemd/system/storADEserver.service || cd ~/ && git clone https://github.com/adeptio-project/adeptioStorade.git

# Check if we have storADEupdater.service?
test -e /etc/systemd/system/storADEupdater.service || echo 'Creating systemD service...'
test -e /etc/systemd/system/storADEupdater.service || sudo cat << EOF > /etc/systemd/system/storADEupdater.service
[Unit]
Description=storADEupdater.service

[Service]
Type=oneshot
WorkingDirectory=$HOME/adeptioStorade
ExecStart=$HOME/adeptioStorade/storADEserver-updater.sh
PrivateTmp=true"
EOF

# Check if we have storADEupdater.timer?
test -e /etc/systemd/system/storADEupdater.timer || echo 'Creating systemD service...'
test -e /etc/systemd/system/storADEupdater.timer || sudo cat << EOF > /etc/systemd/system/storADEupdater.timer
[Unit]
Description=Run storADEupdater unit daily @ 00:00:00 (UTC)

[Timer]
OnCalendar=*-*-* 00:00:00
Unit=storADEupdater.service
Persistent=true

[Install]
WantedBy=timers.target
EOF

# Permissions
sudo chmod 664 /etc/systemd/system/storADEupdater.service
sudo chmod 664 /etc/systemd/system/storADEupdater.timer

# Enable services
systemctl daemon-reload
sudo systemctl start storADEupdater.service
sudo systemctl start storADEupdater.timer
sudo systemctl enable storADEupdater.service
sudo systemctl enable storADEupdater.timer

# Check if we have storADEserver.service?
test -e /etc/systemd/system/storADEserver.service || echo 'Creating systemD service...'
test -e /etc/systemd/system/storADEserver.service || sudo cat << EOF > /etc/systemd/system/storADEserver.service
[Unit]
Description=Adeptio storADEserver daemon for encrypted file storage
After=network.target
[Service]
User=$USER
Type=simple
WorkingDirectory=$HOME/adeptioStorade
ExecStart=$(which python) $HOME/adeptioStorade/storADEserver.py
Restart=always
RestartSec=3600
[Install]
WantedBy=default.target
EOF

sudo chmod 664 /etc/systemd/system/storADEserver.service
systemctl daemon-reload
sudo systemctl enable storADEserver.service
sudo systemctl start storADEserver.service

# Ufw
sudo ufw allow 9079/tcp
sudo ufw allow 9079/udp

echo 'AdeptioCore successfully installed...'
