#!/usr/bin/env bash

#:: Adeptio dev team
#:: Copyright // 2019-01-08
#:: Version: v2.0.0.0

set -e
Intall_log='/var/log/syslog'

echo 'Installing adeptio-qt...'

cp /usr/share/applications/adeptio-qt.desktop ~/Desktop/
chmod +x ~/Desktop/adeptio-qt.desktop

echo 'adeptio-qt successfully installed...'
